/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front_End;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.SwingUtilities;
import java.io.*;

/**
 *
 * @author jonat
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        
        
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Full Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 70, 15);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(260, 190, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Zipcode");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 170, 90, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Address 1");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 80, 90, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("State");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 70, 32, 15);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(260, 90, 50, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Address 2");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 140, 90, 15);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(20, 40, 160, 30);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(20, 100, 160, 30);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(20, 160, 160, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(20, 220, 160, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("City");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 200, 90, 15);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(210, 260, 180, 30);

        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("INVALID CHARACTERS");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 70, 160, 13);

        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("MAX 50 CHARACTERS");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 70, 160, 13);

        jLabel19.setForeground(new java.awt.Color(0, 0, 204));
        jLabel19.setText("REQUIRED");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 70, 160, 13);

        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("MAX 100 CHARACTERS");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 190, 160, 13);

        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setText("REQUIRED");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 130, 160, 13);

        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("MAX 100 CHARACTERS");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 130, 160, 13);

        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("REQUIRED");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(260, 120, 130, 13);

        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("MAX 100 CHARACTERS");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 250, 160, 13);

        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("REQUIRED");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 250, 160, 13);

        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setText("MAX 9 CHARACTERS");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(230, 220, 140, 13);

        jLabel17.setForeground(new java.awt.Color(0, 0, 204));
        jLabel17.setText("MIN 3 CHARACTERS");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(230, 220, 140, 13);

        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setText("INVALID CHARACTERS");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(230, 220, 140, 13);

        jLabel20.setForeground(new java.awt.Color(0, 0, 204));
        jLabel20.setText("REQUIRED");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(260, 220, 90, 13);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\jonat\\OneDrive\\Desktop\\School\\Summer2019\\SoftwareDevelopment\\assignment2\\registerbackground.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = jTextField5.getText();
        String A1 = jTextField6.getText();
        String A2 = jTextField7.getText();
        String City = jTextField3.getText();
        String Zip = jTextField2.getText();
        int flag =0;
        
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        
        // NAME CHECK
        if (name.length()==0){
            jLabel19.setVisible(true);
            flag =1;
        }
        else if (name.length()>50){
            jLabel8.setVisible(true);
            flag = 1;
        }
        else{
            for(int x = 0; x<name.length();x++){
                if (name.charAt(x)=='1'||name.charAt(x)=='2'||name.charAt(x)=='3'||name.charAt(x)=='4'||name.charAt(x)=='5'||name.charAt(x)=='6'||name.charAt(x)=='7'||name.charAt(x)=='8'||name.charAt(x)=='9'){
                    jLabel9.setVisible(true);
                    flag = 1;
                    break;
                }
            }
        }
        
        // ADDRESS' CHECK
        if (A1.length() ==0){
            jLabel11.setVisible(true);
            flag =1;
        }
        else if(A1.length()>100){
            flag = 1;
            jLabel12.setVisible(true);
        }
        
        if (A2.length()>100){
            flag = 1;
            jLabel10.setVisible(true);
        }
        
        if (City.length()==0){
            flag = 1;
            jLabel15.setVisible(true);
        }
        else if(City.length() > 100){
            flag = 1;
            jLabel4.setVisible(true);
        }
        
        if (Zip.length()< 3 && Zip.length()>0){
            flag = 1;
            jLabel17.setVisible(true);
        }
        else if(Zip.length()>9){
            flag =1;
            jLabel16.setVisible(true);
        }
        else if(Zip.length()==0){
            flag =1;
            jLabel20.setVisible(true);
        }
        else{
            for(int x = 0; x<Zip.length();x++){
                if (Zip.charAt(x)!='1'&&Zip.charAt(x)!='2'&&Zip.charAt(x)!='3'&&Zip.charAt(x)!='4'&&Zip.charAt(x)!='5'&&Zip.charAt(x)!='6'&&Zip.charAt(x)!='7'&&Zip.charAt(x)!='8'&&Zip.charAt(x)!='9'){
                    jLabel18.setVisible(true);
                    flag = 1;
                    break;
                }
            }
        }
        
        if(flag == 0){
            setVisible(false);
            FuelForm form = new FuelForm(A1);
            form.setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
